nohup awk '{if($1=="chr1") print $0}' $1 > chr1_bin.txt &
nohup awk '{if($1=="chr2") print $0}' $1 > chr2_bin.txt &
nohup awk '{if($1=="chr3") print $0}' $1 > chr3_bin.txt &
nohup awk '{if($1=="chr4") print $0}' $1 > chr4_bin.txt &
nohup awk '{if($1=="chr5") print $0}' $1 > chr5_bin.txt &
nohup awk '{if($1=="chr6") print $0}' $1 > chr6_bin.txt &
nohup awk '{if($1=="chr7") print $0}' $1 > chr7_bin.txt &
nohup awk '{if($1=="chr8") print $0}' $1 > chr8_bin.txt &
nohup awk '{if($1=="chr9") print $0}' $1 > chr9_bin.txt &
nohup awk '{if($1=="chr10") print $0}' $1 > chr10_bin.txt &
nohup awk '{if($1=="chr11") print $0}' $1 > chr11_bin.txt &
nohup awk '{if($1=="chr12") print $0}' $1 > chr12_bin.txt &
nohup awk '{if($1=="chr13") print $0}' $1 > chr13_bin.txt &
nohup awk '{if($1=="chr14") print $0}' $1 > chr14_bin.txt &
nohup awk '{if($1=="chr15") print $0}' $1 > chr15_bin.txt &
nohup awk '{if($1=="chr16") print $0}' $1 > chr16_bin.txt &
nohup awk '{if($1=="chr17") print $0}' $1 > chr17_bin.txt &
nohup awk '{if($1=="chr18") print $0}' $1 > chr18_bin.txt &
nohup awk '{if($1=="chr19") print $0}' $1 > chr19_bin.txt &
nohup awk '{if($1=="chr20") print $0}' $1 > chr20_bin.txt &
nohup awk '{if($1=="chr21") print $0}' $1 > chr21_bin.txt &
nohup awk '{if($1=="chr22") print $0}' $1 > chr22_bin.txt &
nohup awk '{if($1=="chrX") print $0}' $1 > chrX_bin.txt &
nohup awk '{if($1=="chrY") print $0}' $1 > chrY_bin.txt &
nohup awk '{if($1=="chrM") print $0}' $1 > chrM_bin.txt &
