nohup awk '{if($1=="chr1") print $0}' $1 > chr1_bedgraph.txt &
nohup awk '{if($1=="chr2") print $0}' $1 > chr2_bedgraph.txt &
nohup awk '{if($1=="chr3") print $0}' $1 > chr3_bedgraph.txt &
nohup awk '{if($1=="chr4") print $0}' $1 > chr4_bedgraph.txt &
nohup awk '{if($1=="chr5") print $0}' $1 > chr5_bedgraph.txt &
nohup awk '{if($1=="chr6") print $0}' $1 > chr6_bedgraph.txt &
nohup awk '{if($1=="chr7") print $0}' $1 > chr7_bedgraph.txt &
nohup awk '{if($1=="chr8") print $0}' $1 > chr8_bedgraph.txt &
nohup awk '{if($1=="chr9") print $0}' $1 > chr9_bedgraph.txt &
nohup awk '{if($1=="chr10") print $0}' $1 > chr10_bedgraph.txt &
nohup awk '{if($1=="chr11") print $0}' $1 > chr11_bedgraph.txt &
nohup awk '{if($1=="chr12") print $0}' $1 > chr12_bedgraph.txt &
nohup awk '{if($1=="chr13") print $0}' $1 > chr13_bedgraph.txt &
nohup awk '{if($1=="chr14") print $0}' $1 > chr14_bedgraph.txt &
nohup awk '{if($1=="chr15") print $0}' $1 > chr15_bedgraph.txt &
nohup awk '{if($1=="chr16") print $0}' $1 > chr16_bedgraph.txt &
nohup awk '{if($1=="chr17") print $0}' $1 > chr17_bedgraph.txt &
nohup awk '{if($1=="chr18") print $0}' $1 > chr18_bedgraph.txt &
nohup awk '{if($1=="chr19") print $0}' $1 > chr19_bedgraph.txt &
nohup awk '{if($1=="chr20") print $0}' $1 > chr20_bedgraph.txt &
nohup awk '{if($1=="chr21") print $0}' $1 > chr21_bedgraph.txt &
nohup awk '{if($1=="chr22") print $0}' $1 > chr22_bedgraph.txt &
nohup awk '{if($1=="chrX") print $0}' $1 > chrX_bedgraph.txt &
nohup awk '{if($1=="chrY") print $0}' $1 > chrY_bedgraph.txt &
nohup awk '{if($1=="chrM") print $0}' $1 > chrM_bedgraph.txt &
